version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app:rw
      - ./backend/artifacts:/app/artifacts:rw
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - '3000:5173'
    env_file:
      - ./.env
