name: bc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - xgboost
  - fastapi
  - uvicorn
  - python-multipart
  - aiofiles
  - pip
  - pip:
    # add pip-only packages here if needed
    - ""
